variables:
 - group : terraformvariables

trigger:
  batch: true # batch changes if true (the default); start a new build for every push if false
  branches:
    include:
      - master
pr: none

pool:
  vmImage: ubuntu-latest

steps:

- task: CmdLine@2
  inputs:
    script: |
      echo  '$(System.DefaultWorkingDirectory)'
      dir
      dir subfoldername
